name: GitHub Actions Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build with Docker
      uses: docker/build-push-action@v6
      with: 
        context: .
        push: true
        tags: michaelaviram/java-app:latest
  """    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_KEY }}
      run:  |
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ec2-user@3.65.196.15 '
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker run michaelaviram/java-app
        '
  """"


