name: GitHub Actions Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Bump Build
      id: bump
      uses: nnichols/maven-version-bump-action@v3

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact-${{steps.bump.outputs.version}}
        path: /home/runner/work/simple-java-maven-app/simple-java-maven-app/target/my-app-1.0-SNAPSHOT.jar
